import api from './api'
export const getAdminStats = () => api.get('/admin/stats')
export const toggleTenantStatus = (id) => api.put(`/admin/tenants/${id}/toggle-status`)
export const getAdminActivityLogs = (params) => api.get('/admin/activity-logs', { params })
export const getTenantUsers = (id) => api.get(`/admin/tenants/${id}/users`)
export const createTenantUser = (id, data) => api.post(`/admin/tenants/${id}/users`, data)
export const updateTenantUser = (id, userId, data) => api.put(`/admin/tenants/${id}/users/${userId}`, data)
export const broadcastNotification = (data) => api.post('/admin/notifications/broadcast', data)
export const getBroadcastNotifications = () => api.get('/admin/notifications/broadcast')
export const getRateHistory = (days) => api.get('/admin/rate-history', { params: { days } })
export const getAccessRequests = (params) => api.get('/admin/requests', { params })
export const getAccessRequest = (id) => api.get(`/admin/requests/${id}`)
export const approveAccessRequest = (id, data) => api.post(`/admin/requests/${id}/approve`, data)
export const rejectAccessRequest = (id, data) => api.post(`/admin/requests/${id}/reject`, data)
